package com.tolochko.periodicals.model.connection;

import com.tolochko.periodicals.model.dao.exception.TransactionException;
import org.apache.log4j.Logger;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ConnectionProxyImpl implements ConnectionProxy {
    private static final Logger logger = Logger.getLogger(ConnectionProxyImpl.class);
    private static final String CAN_NOT_BEGIN_TRANSACTION = "Can not begin transaction.";
    private static final String CAN_NOT_COMMIT_TRANSACTION = "Can not commit transaction";
    private static final String CAN_NOT_ROLLBACK_TRANSACTION = "Can not rollback transaction";
    private static final String CAN_NOT_CLOSE_CONNECTION = "Can not close connection";

    private Connection connection;
    private boolean transactionBegun = false;

    public ConnectionProxyImpl(Connection connection) {
        this.connection = connection;
    }

    @Override
    public void beginTransaction() {
        try {
            connection.setAutoCommit(false);
            transactionBegun = true;
            logger.debug("Transaction begun");
        } catch (SQLException e) {
            logger.error(CAN_NOT_BEGIN_TRANSACTION, e);
            throw new TransactionException(CAN_NOT_BEGIN_TRANSACTION, e);
        }
    }

    @Override
    public void commitTransaction() {
        try {
            connection.commit();
            connection.setAutoCommit(true);
            connection.close();
            logger.debug("Transaction committed");
        } catch (SQLException e) {
            throw new TransactionException(CAN_NOT_COMMIT_TRANSACTION, e);
        }
    }

    @Override
    public void rollbackTransaction() {
        try {
            logger.debug("trying to rollback transaction");
            connection.rollback();
            connection.setAutoCommit(true);
            connection.close();
            logger.debug("rollback success");
        } catch (SQLException e) {
            throw new TransactionException(CAN_NOT_ROLLBACK_TRANSACTION, e);
        }
    }

    @Override
    public void close() {
        try {
            if (!transactionBegun) {
                connection.close();
            }
        } catch (SQLException e) {
            logger.error(CAN_NOT_CLOSE_CONNECTION, e);
            throw new TransactionException(CAN_NOT_CLOSE_CONNECTION, e);
        }
    }

    @Override
    public PreparedStatement prepareStatement(String query) throws SQLException {
        return connection.prepareStatement(query);
    }

    @Override
    public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(query, autoGeneratedKeys);
    }

    public Connection getConnection() {
        return connection;
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }
}
